---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 16.06.2020 19:24
---

DisarmID = FourCC('Abun')
DisarmTable = {}
function DisarmUnitTimed(hero, sec)
	DisarmUnit(hero,true)
	TimerStart(CreateTimer(), sec, false, function()
		UnitRemoveAbility(hero, DisarmID)
		DisarmUnit(hero,false)
	end)
end

function IsUnitDisarmedCounted(hero)
	return GetUnitAbilityLevel(hero, DisarmID) > 0, DisarmTable[GetHandleId(hero)]
end

function DisarmUnit(hero, state)
	if not DisarmTable[GetHandleId(hero)] then
		DisarmTable[GetHandleId(hero)] = 0
		UnitAddAbility(hero, DisarmID)
		BlzUnitHideAbility(hero, DisarmID, false)
		UnitRemoveAbility(hero, DisarmID)
		--print("первое появление")
	end
	if state then
		DisarmTable[GetHandleId(hero)] = DisarmTable[GetHandleId(hero)] + 1
		if DisarmTable[GetHandleId(hero)]>=1 then
			UnitAddAbility(hero, DisarmID)
		end
	else
		DisarmTable[GetHandleId(hero)] = DisarmTable[GetHandleId(hero)] -1
		if DisarmTable[GetHandleId(hero)]<=0 then
			UnitRemoveAbility(hero, DisarmID)
			DisarmTable[GetHandleId(hero)]=nil
		end
	end
end

-- есть альтернатива для BlzUnitDisableAbility( unit,FourCC( "Aatk" ), true, false )