---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 16.06.2020 19:24
---

DisarmID=FourCC('Abun')

function DisarmUnitTimed(hero,sec)
	UnitAddAbility(hero,DisarmID)
	BlzUnitHideAbility(hero,DisarmID,false)
	TimerStart(CreateTimer(), sec, false, function()
		UnitRemoveAbility(hero,DisarmID)
	end)
end

function DisarmUnitTimedGetState(hero)
	return GetUnitAbilityLevel(hero,DisarmID)>0
end

function DisarmUnit(hero)
	UnitAddAbility(hero,DisarmID)
	BlzUnitHideAbility(hero,DisarmID,false)
end