---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 13.06.2020 3:35
function UnitStealMana(hero,target,amount)
	local stealMana=GetUnitState(target,UNIT_STATE_MANA)
	UnitAddMana(target,-amount)
	FlyTextTagManaBurn(target,-R2I(amount),GetOwningPlayer(target))
	if stealMana<=amount then amount=stealMana end
	local losingMana=BlzGetUnitMaxMana(hero)-GetUnitState(hero,UNIT_STATE_MANA)
	--print("недостаток маны="..losingMana)
	if losingMana<=amount then amount=losingMana end
	UnitAddMana(hero,amount)
	FlyTextTagManaBurn(hero,R2I(amount),GetOwningPlayer(hero))
end

function UnitAddMana(target,amount)
	SetUnitState(target,UNIT_STATE_MANA,GetUnitState(target,UNIT_STATE_MANA)+amount)
end