---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 10.01.2020 22:05
--
---Глобалки
TIMER_PERIOD = 0.03125
HERO={}
do
	local InitGlobalsOrigin = InitGlobals -- записываем InitGlobals в переменную
	function InitGlobals()
		InitGlobalsOrigin() -- вызываем оригинальную InitGlobals из переменной
		--InitGameCore()
		--InitMouseMoveTrigger()
		InitDamage()
		InitSpellTrigger()
		InitUnitDeath()
		--InitAllZones()
		LeavePlayer()
		LearnEvent()
		--BadChat() -- Функция для починки чата
	end

end