---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 30.04.2020 0:04
stuneff="Abilities\\Spells\\Human\\Thunderclap\\ThunderclapTarget"
StunSystem={}
function StunUnit(hero,dur)
	if not StunSystem[GetHandleId(hero)] then
	--	print("оглушен первый раз")
		StunSystem[GetHandleId(hero)]={
			Time=0,
			Eff=nil
		}
	end
	local data=StunSystem[GetHandleId(hero)]
	--print(1)

	if not data.eff then DestroyEffect(data.eff) end

	--print(2)

	data.Eff=AddSpecialEffectTarget(stuneff,hero,"overhead")

	local curdur=0
	if data.Time<dur and data.Time==0 then
		--print("полное оглушение, обновляем")
		data.Time=dur
	else
		print("Есть более долгое оглушение")
		return
		--dur=data.Time
	end

	BlzPauseUnitEx(hero,true)

	TimerStart(CreateTimer(), 0.1, true, function()
		curdur=curdur+0.1
	--	print(data.Time)
		data.Time=data.Time-0.1
		if curdur>=dur then
			BlzPauseUnitEx(hero,false)
		--	print("end")
			DestroyTimer(GetExpiredTimer())
			data.Time=0
			DestroyEffect(data.Eff)
		end
	end)
end