---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 23.01.2020 20:11
function InitUnitDeath()
	local gg_trg_DEADGUI = CreateTrigger()
	TriggerRegisterAnyUnitEventBJ(gg_trg_DEADGUI, EVENT_PLAYER_UNIT_DEATH)--меня полностью устраивает это событие
	TriggerAddAction(gg_trg_DEADGUI, function()
		--print("EventDead")
		local DeadUnit=GetTriggerUnit()--умерший
		local Killer=GetKillingUnit()--убийца

		if IsUnitType(DeadUnit,UNIT_TYPE_HERO) then --герой умер
			local x,y=GetUnitXY(DeadUnit)

			if GetUnitAbilityLevel(DeadUnit,FourCC('A005'))>0 then
				local spirit=CreateUnit(GetOwningPlayer(DeadUnit),FourCC('u000'),x,y,0)
				local lvl=GetUnitAbilityLevel(DeadUnit,FourCC('A005'))
				local ms=180+(30*lvl)
				SetUnitMoveSpeed(spirit,ms)
				--print("Смерть героя - лечение x"..x)
				local e

				local k=5*(lvl+1)
				GroupEnumUnitsInRange(perebor,x,y,600,nil)
				while true do
					--print("группа")
					e = FirstOfGroup(perebor)
					--print(GetUnitName(e).." в FirstOFGroup")
					if e == nil then break end
					--print(GetUnitName(e).." в переборе")
					if UnitAlive(e) and IsUnitAlly(e,GetOwningPlayer(DeadUnit)) and not IsUnitType(e,UNIT_TYPE_MECHANICAL) then
						local amount=BlzGetUnitMaxHP(e)*k*0.01
						--print("Лечим"..GetUnitName(e)..amount)
						HealUnit(e,amount)
					end
					GroupRemoveUnit(perebor,e)
				end
				TimerStart(CreateTimer(), 1, true, function() -- ждём возраждения героя чтобы убить духа3
					if UnitAlive(DeadUnit) then
						print("Дух умер, так как герой возродился")
						DestroyTimer(GetExpiredTimer())
						KillUnit(spirit)
					end
				end)
			end
		end

		if IsUnitType(Killer,UNIT_TYPE_HERO) then --герои убил кого-то
			if GetUnitAbilityLevel(Killer,FourCC('A00B'))>0 then
				SetUnitUserData(Killer,1+GetUnitUserData(Killer))
			end

			if GetUnitAbilityLevel(Killer,FourCC('A00S'))>0 then --Оживщий огонь
				SetUnitUserData(Killer,1+GetUnitUserData(Killer))
			end
			if GetUnitAbilityLevel(Killer,FourCC('A00X'))>0 then --Исцеление
				local lvl=GetUnitAbilityLevel(Killer,FourCC('A00X'))
				local amountU={25,32,40,50}
				local amountH={15,20,25,30}
				local heal=0
				if IsUnitType(DeadUnit,UNIT_TYPE_HERO) then
					heal=BlzGetUnitMaxHP(Killer)*0.01*amountH[lvl]
				else
					heal=amountU[lvl]
				end
				HealUnit(Killer,heal)
				DestroyEffect(AddSpecialEffectTarget("Abilities\\Spells\\Human\\HolyBolt\\HolyBoltSpecialArt",Killer,"origin"))
			end
		end
		-- просто кто-то умер
		if IsUnitType(DeadUnit,UNIT_TYPE_HERO) and GetUnitAbilityLevel(Killer,FourCC('A014'))>0 and IsUnitInRangeXY(DeadUnit,IceBlast[1],IceBlast[2],325) then
			CreateIceBlast(IceBlast[3],FourCC('A014'),GetUnitXY(DeadUnit))
		end

	end)
end