do -- BD
    function SimpleID2FourCC(...) --неизвестное число аргументов  от 4 до 8 пример A00O,A00Z,A010,A011
        local table={...}
        for i = 1, #table do
           if table[i] then
                table[i]=FourCC(table[i])
           end
        end
        return table
    end
    TalonBD={
        [1]={ --Падший король H00S A00O,A00Z,A010,A011
            Ability=SimpleID2FourCC("A00O","A00Z","A010","A011"),
            --Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNAvatar.blp", --каждому герою добавить путь до портрета
            description={
                "+2 регенерации маны",
                "",
                "+20 урона",
                "+75 к урону от \nмолний",
                "",
                "+8 к силе",
                "+100 к сильному \nудару",
                "",
                "Цепь молний без \nперезарядки",
                "+18 процентов шанса\n удар молнии",
                "",
                "+50 скорости \nперемещения",
                "-50 сек перезарядки \nпробуждения",
                "",
                "Сильный удар \nстановится пассивным",

            },
            Icons={
                "ReplaceableTextures\\CommandButtons\\BTNManaStone.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNAttack.blp",
                "ReplaceableTextures\\CommandButtons\\BTNH00SLightingChain.blp",
                "",
                "UI\\Widgets\\Console\\Human\\infocard-heroattributes-str.blp",
                "ReplaceableTextures\\CommandButtons\\BTNH00SIronHit.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNH00SLightingChain.blp",
                "ReplaceableTextures\\CommandButtons\\BTNH00SLightingChain.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNSlippersOfAgility.blp",
                "ReplaceableTextures\\CommandButtons\\BTNAvatarOn.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNH00SIronHit.blp",
            }
        },
        [2]={ -- Провидец Пустоты H00X
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNFacelessOne.blp",
            description={
                "+150 к здоровью",
                "",
                "-15%% перезарядки \nспособностей",
                "+2 существа \nПаразит",
                "",
                "+40 к урону",
                "+20%% урона по постройкам \nКритический удар",
                "",
                "+2 к минимальному \nоглушению",
                "+Критический удар наносит \nурон по области 500",
                "",
                "+15%% к уклонению",
                "100%% шанс молний",
                "",
                "Ярость превращается \nв ауру",

            },
            Icons={
                "ReplaceableTextures\\CommandButtons\\BTNHealthStone.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNEngineeringUpgrade.blp",
                "ReplaceableTextures\\CommandButtons\\BTNH00XParasite.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNAttack.blp",
                "ReplaceableTextures\\CommandButtons\\BTNCriticalStrike.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNOrbOfLightning.blp",
                "ReplaceableTextures\\CommandButtons\\BTNCriticalStrike.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNHoldPosition.blp",
                "ReplaceableTextures\\CommandButtons\\BTNOrbOfLightning.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNH00XRage.blp",

            }

        },
        [3]={ -- Хранитель сада H012
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNGreenDragonSpawn.blp",
            description={
                "+200 к здоровью",
                "",
                "-8 перезарядки \nПрорыв",
                "+15 к ловкости",
                "",
                "+20 к скорости \nперемещения",
                "+1 урон за ловкость \nЛесное колдовство",
                "",
                "+200 к радиусу урона \nЛесное колдовство",
                "+25%% урона от \nспособностей",
                "",
                "+50 урона",
                "+15 ко всем \nхарактеристикам",
                "",
                "+110 урона за врага \nСокрушающий удар",

            },
            Icons={
                "ReplaceableTextures\\CommandButtons\\BTNHealthStone.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNpurpleDragonSpawn.blp",
                "UI\\Widgets\\Console\\Human\\infocard-heroattributes-agi.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNSlippersOfAgility.blp",
                "ReplaceableTextures\\CommandButtons\\BTNH012NatureMagic.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNH012NatureMagic.blp",
                "ReplaceableTextures\\CommandButtons\\BTNEngineeringUpgrade.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNAttack.blp",
                "UI\\Widgets\\Console\\Human\\infocard-heroattributes-agi.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNH012CriticallHit.blp",
            }

        },
        [4]={ -- Несущий огонь H00Q
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNVolcanus.blp",
            description={
                "+3 к зарядам \nОживший огонь",
                "",
                "+20 урона",
                "+10%% к длительности \nспособностей",
                "",
                "+20 к скорости \nперемещения",
                "+20 урона за заряд \nОгненная буря",
                "",
                "+24 к силе",
                "+120 урона Инферно",
                "",
                "Инферно не требует маны",
                "-50 перезарядки \nОгненная буря",
                "",
                "+3 к длительности оглушения \nОгненный шар",

            },
            Icons={
                "ReplaceableTextures\\CommandButtons\\BTNH00QResurgentTheFire.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNAttack.blp",
                "ReplaceableTextures\\CommandButtons\\BTNEngineeringUpgrade.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNSlippersOfAgility.blp",
                "ReplaceableTextures\\CommandButtons\\BTNH00QFirestorm.blp",
                "",
                "UI\\Widgets\\Console\\Human\\infocard-heroattributes-str.blp",
                "ReplaceableTextures\\CommandButtons\\BTNH00QInferno.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNH00QInferno.blp",
                "ReplaceableTextures\\CommandButtons\\BTNH00QFirestorm.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNH00QFireball.blp",
            }

        },
        [5]={ -- Королева Бездны H00H
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNBlueDemoness.blp",
            description={
                "+20 урона",
                "",
                "-6 перезарядки \nТемной стаи",
                "+5 ловкости",
                "",
                "+30 к урону \nТемной стаи",
                "+9%% к уклонению \nТишина Бездны",
                "",
                "+300 к здоровью",
                "+25 скорости \nперемещения",
                "",
                "+2 к длительности страха \nУжасающий вой",
                "+25 ловкости",
                "",
                "Темная стая не требует \nманы",

            },
            Icons={
                "ReplaceableTextures\\CommandButtons\\BTNAttack.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNCarrionSwarm.blp",
                "UI\\Widgets\\Console\\Human\\infocard-heroattributes-agi.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNCarrionSwarm.blp",
                "ReplaceableTextures\\CommandButtons\\BTNAuraOfDarkness.blp",
                "",
                "UI\\Widgets\\Console\\Human\\infocard-heroattributes-str.blp",
                "ReplaceableTextures\\CommandButtons\\BTNSlippersOfAgility.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNLionHorn.blp",
                "UI\\Widgets\\Console\\Human\\infocard-heroattributes-agi.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNCarrionSwarm.blp",
            }

        },
        [6]={ -- Ледяная виверна H00J
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNAzureDragon.blp",
            description={
                "+50 урона",
                "",
                "-4 перезарядки \nХолодное обьятие",
                "+300 к дальности \nобзора ночью",
                "",
                "+180 к урону от взрыва",
                "+12%% замедления от \nхолода",
                "",
                "+50 к лечению \nХолодное обьятие",
                "+3 к длительности вихря",
                "",
                "-40 перезарядки \nЛедяная волна",
                "+300 к области взрыва",
                "",
                "+30 разума",

            },
            Icons={
                "ReplaceableTextures\\CommandButtons\\BTNAttack.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNDarkRitual.blp",
                "ReplaceableTextures\\PassiveButtons\\PASBTNElunesBlessing.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNGlacier.blp",
                "ReplaceableTextures\\CommandButtons\\BTNBreathOfFrost.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNDarkRitual.blp",
                "ReplaceableTextures\\CommandButtons\\BTNBlizzard.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNBlizzard.blp",
                "ReplaceableTextures\\CommandButtons\\BTNGlacier.blp",
                "",
                "UI\\Widgets\\Console\\Human\\infocard-heroattributes-int.blp",
            }

        },
        [7]={ -- Архикрыса H007
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNKoboldGeomancer.blp",
            description={
                "+50 поглощения маны",
                "",
                "+10 разума",
                "+180 здоровья",
                "",
                "+2 к длительности \nразлома",
                "+20%% урона от \nспособностей",
                "",
                "уменьшение перезарядки на \n50%%",
                "+25 скорости перемещения",
                "",
                "-30 перезарядки Опустошение",
                "+160%% урона разлома",
                "",
                "+20 разума",

            },
            Icons={
                "ReplaceableTextures\\CommandButtons\\BTNH007Absorption.blp",
                "",
                "UI\\Widgets\\Console\\Human\\infocard-heroattributes-int.blp",
                "ReplaceableTextures\\CommandButtons\\BTNHealthStone.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNH007MirrorRift.blp",
                "ReplaceableTextures\\CommandButtons\\BTNEngineeringUpgrade.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNEngineeringUpgrade.blp",
                "ReplaceableTextures\\CommandButtons\\BTNSlippersOfAgility.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNH007Desolation.blp",
                "ReplaceableTextures\\CommandButtons\\BTNH007MirrorRift.blp",
                "",
                "UI\\Widgets\\Console\\Human\\infocard-heroattributes-int.blp",
            }

        },
        [8]={ -- Вампир H008
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNHeroDreadLord.blp",
            description={
                "+5 регенерации здоровья",
                "",
                "-6 перезарядки \nТемная стая",
                "+50 урона",
                "",
                "-30 перезарядки\nПохищение",
                "+26 поглощенного здоровья",
                "",
                "-6 защиты Кошмар",
                "+12 ко всем характеристикам",
                "",
                "Запах крови не требует маны",
                "+2000 к дальности применения Темная стая",
                "",
                "+70%% иммунитета к страху",

            },
            Icons={
                "ReplaceableTextures\\CommandButtons\\BTNHealthStone.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNCarrionSwarm.blp",
                "ReplaceableTextures\\CommandButtons\\BTNAttack.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNDevourMagic.blp",
                "ReplaceableTextures\\CommandButtons\\BTNAdvancedUnholyStrength.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNH008Fear.blp",
                "UI\\Widgets\\Console\\Human\\infocard-heroattributes-all.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNAdvancedUnholyStrength.blp",
                "ReplaceableTextures\\CommandButtons\\BTNCarrionSwarm.blp",
                "",
                "UI\\Widgets\\Console\\Human\\infocard-heroattributes-str.blp",
            }

        },
        [9]={ -- Вождь троллей H009
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNForestTrollWarlord.blp",
            description={
                "-4 к перезарядки \nЛовчий",
                "",
                "+250 здоровья",
                "+4 к длительности \nТанец троллей",
                "",
                "Ловчий проходит сквозь \nневосприимчивость к магии",
                "+1800 к радиусу \nКомандирская аура",
                "",
                "+4 макс. длительности \nЛовчий",
                "Случайная сеть",
                "",
                "+80 урона",
                "-40 перезарядки \nТанец троллей",
                "",
                "Топоры можно применять \nна союзников",

            },
            Icons={
                "ReplaceableTextures\\CommandButtons\\BTNH009Ensnare.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNHealthStone.blp",
                "ReplaceableTextures\\CommandButtons\\BTNH009Trolldance.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNH009Ensnare.blp",
                "ReplaceableTextures\\CommandButtons\\BTNH009WarlordAura.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNH009Ensnare.blp",
                "ReplaceableTextures\\CommandButtons\\BTNH009Ensnare.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNAttack.blp",
                "ReplaceableTextures\\CommandButtons\\BTNH009Trolldance.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNH009Axes.blp",
            }

        },
        [10]={ -- Волшебница H00A
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNJainasea.blp",
            description={
                "+10 скорости \nперемещения",
                "",
                "+100 маны",
                "+4%% урона \nТелепатия",
                "",
                "+20 урона",
                "-2 перезарядки \nЗлые чары",
                "",
                "+2 к длительности \nТелепатия",
                "+200 дальности применения \nспособностей",
                "",
                "+450 обзора ночью",
                "+30%% иммунитета к \nоглушению",
                "",
                "-40 перезарядки \nОгненный щит",

            },
            Icons={
                "ReplaceableTextures\\CommandButtons\\BTNSlippersOfAgility.blp",
                "",
                "ReplaceableTextures\\CommandButton\\BTNManaStone.blp",
                "ReplaceableTextures\\CommandButtons\\BTNGhost.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNAttack.blp",
                "ReplaceableTextures\\CommandButtons\\BTNCritterChicken.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNGhost.blp",
                "ReplaceableTextures\\CommandButtons\\BTNEngineeringUpgrade.blp",
                "",
                "ReplaceableTextures\\PassiveButtons\\PASBTNElunesBlessing.blp",
                "ReplaceableTextures\\CommandButtons\\BTNDefendStop.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNInvulnerable.blp",
            }

        },
        [11]={ -- Вурдалак H00B
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNGhoul.blp",
            description={
                "+2%% Голод",
                "",
                "+2 к длительности \nДобыча",
                "+50 урона",
                "",
                "-3 к перезарядки \nОстрые когти",
                "+16 регенерации здоровья \nБезумие",
                "",
                "+70 поглощения здоровья \nОстрые когти",
                "+12 ловкость",
                "",
                "-20 к перезарядки \nБезумие",
                "+1 заряд Добыча",
                "",
                "+50%% урона по постройкам",

            },
            Icons={
                "ReplaceableTextures\\CommandButtons\\BTNCannibalize.blp",
                "",
                "ReplaceableTextures\\PassiveButtons\\PASBTNExhumeCorpses.blp",
                "ReplaceableTextures\\CommandButtons\\BTNAttack.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNCreatureAttack.blp",
                "ReplaceableTextures\\CommandButtons\\BTNAdvancedCreatureAttack.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNCreatureAttack.blp",
                "UI\\Widgets\\Console\\Human\\infocard-heroattributes-agi.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNAdvancedCreatureAttack.blp",
                "ReplaceableTextures\\PassiveButtons\\PASBTNExhumeCorpses.blp",
                "",
                "ReplaceableTextures\\PassiveButtons\\PASBTNDemolish.blp",
            }

        },
        [12]={ -- Госпожа средних миров H00D
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNfemalemetamorphosis.blp",
            description={
                "+8 к длительности \nподчиненного существа",
                "",
                "+15%% скорости атаки",
                " -10%% перезарядки \nспособностей",
                "",
                "+8 сила",
                "-4 к перезарядки \nПроклятие",
                "",
                "+500 здоровья",
                "+12 к длительности \nПоглощения души",
                "",
                "+50 скорости перемещения",
                "+30%% замедления \nПроклятие",
                "",
                "+150 урона",

            },
            Icons={
                "ReplaceableTextures\\CommandButtons\\BTNH00DSubjection.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNAttack.blp",
                "ReplaceableTextures\\CommandButtons\\BTNEngineeringUpgrade.blp",
                "",
                "UI\\Widgets\\Console\\Human\\infocard-heroattributes-str.blp",
                "ReplaceableTextures\\CommandButtons\\BTNH00DDamnation.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNHealthStone.blp",
                "ReplaceableTextures\\CommandButtons\\BTNH00DAbsorbOfSoul.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNSlippersOfAgility.blp",
                "ReplaceableTextures\\CommandButtons\\BTNH00DDamnation.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNAttack.blp",
            }

        },
        [13]={ -- Дух пространства H00F
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNGhost.blp",
            description={
                "+4 урона в секунду \nДух",
                "",
                "+250 к дальности применения \nспособностей",
                "-10%% перезарядки способностей",
                "",
                "+10%% вампиризма от \nспособностей",
                "+700 здоровье трупа",
                "",
                "+20 регенерации \nГнилая плоть",
                "+2 секунды оглушения \nКогти",
                "",
                "+5 поглощения маны",
                "Труп может использовать \nспособности духа",
                "",
                "+120 урона духа",

            },
            Icons={
                "ReplaceableTextures\\CommandButtons\\BTNBanshee.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNEngineeringUpgrade.blp",
                "ReplaceableTextures\\CommandButtons\\BTNEngineeringUpgrade.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNEngineeringUpgrade.blp",
                "ReplaceableTextures\\CommandButtons\\BTNHealthStone.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNGiantSkeletonWarrior.blp",
                "ReplaceableTextures\\CommandButtons\\BTNGhoulFrenzy.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNManaDrain.blp",
                "ReplaceableTextures\\CommandButtons\\BTNEngineeringUpgrade.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNAttack.blp",
            }

        },
        [14]={ -- Копатель H00G
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNSnarlmaneTheBloodgorger.blp",
            description={
                "+15 урона",
                "",
                "+4%% шанса Оглушение",
                "+200 обзора ночью",
                "",
                "-30 секунд к перезарядки \nТелескоп",
                "+50%% скорости атаки",
                "",
                "+500 здоровья",
                "+20%% шанс \nКопать",
                "",
                "+15 сила",
                "+3 к длительности \nЗолотая жила",
                "",
                "+300 к дальности \nприменения способностей",

            },
            Icons={
                "ReplaceableTextures\\CommandButtons\\BTNAttack.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNStun.blp",
                "ReplaceableTextures\\PassiveButtons\\PASBTNElunesBlessing.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNTelescope.blp",
                "ReplaceableTextures\\CommandButtons\\BTNAttack.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNHealthStone.blp",
                "ReplaceableTextures\\CommandButtons\\BTNGatherGold.blp",
                "",
                "UI\\Widgets\\Console\\Human\\infocard-heroattributes-str.blp",
                "ReplaceableTextures\\CommandButtons\\BTNChestOfGold.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNEngineeringUpgrade.blp",
            }

        },
        [15]={ -- Крыса H00I
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNKobold.blp",
            description={
                "+20 урона Земельный дым",
                "",
                "+80 здоровья Земельный дым",
                "+500 к дальности применения \nКрысиное мастерство",
                "",
                "+15 ловкости",
                "+4 невидимости",
                "",
                "+2 регенерация маны",
                "-6 защиты Инстинкт",
                "",
                "+10%% вампиризма от \nспособностей",
                "-35%% перезарядки способностей \nи предметов",
                "",
                "+200%% к урону \nБерегите спину",

            },
            Icons={
                "ReplaceableTextures\\CommandButtons\\BTNPipeOfInsight.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNPipeOfInsight.blp",
                "ReplaceableTextures\\PassiveButtons\\PASBTNRegenerationAura.blp",
                "",
                "UI\\Widgets\\Console\\Human\\infocard-heroattributes-agi.blp",
                "ReplaceableTextures\\CommandButtons\\BTNBattleRoar.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNManaStone.blp",
                "ReplaceableTextures\\CommandButtons\\btnscourgebuild.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNEngineeringUpgrade.blp",
                "ReplaceableTextures\\CommandButtons\\BTNEngineeringUpgrade.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNBattleRoar.blp",
            }

        },
        [16]={ -- Ловец духов H00K
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNWitchDoctor.blp",
            description={
                "+10 разума",
                "",
                "+45 золота в минуту",
                "+25%% исцеления Дух",
                "",
                "5%% шанс Нивана”",
                "-15 к перезарядки \nЛечебная волна",
                "",
                "+40 урона",
                "-60 к перезарядки \nКровожадность",
                "",
                "+30 секунд к длительности \nпохищенного атрибута",
                "Дух превращается в \nреинкарнацию",
                "",
                "Лечебная волна имеет \nдва заряда",

            },
            Icons={
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
            }

        },
        [17]={ -- Мать пауков H00M
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNSpiderBlack.blp",
            description={
                "+120 к длительности \nпаучка",
                "",
                "+50 скорости \nперемещения",
                "+3 секунды длительности \nяда",
                "",
                "+3 заряда Порча",
                "+240 урона по цели \nПаразит",
                "",
                "+24 урона паучка",
                "+120 к длительности \nпаутины",
                "",
                "+20 разума",
                "Паутина имеет 3 заряда",
                "",
                "+30\\+8 урона от яда",

            },
            Icons={
                "ReplaceableTextures\\CommandButtons\\BTNH00MParasite.blp",
                "",
                ".blp",
                ".blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNH00MCorruption.blp",
                ".blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNH00MParasite.blp",
                "ReplaceableTextures\\CommandButtons\\BTNH00MWeb.blp",
                "",
                ".blp",
                "ReplaceableTextures\\CommandButtons\\BTNH00MWeb.blp",
                "",
                ".blp",
            }

        },
        [18]={ -- Молотобоец H00N
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNHeroMountainKing.blp",
            description={
                "+5 сила",
                "",
                "+50 урона Молот бурь",
                "Громовой удар снижает защиту \nпротивника на 2 ед.",
                "",
                "+3 регенерации маны",
                "+6%% шанс на оглушение \nЧемпион",
                "",
                "+10 ко всем характеристикам",
                "Молот бурь по 3 целям",
                "",
                "+1 к длительности \nоглушения Чемпион",
                "Берсерк имеет 3 заряда",
                "",
                "-50%% перезарядки способностей",

            },
            Icons={
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
            }

        },
        [19]={ -- Некромант H00O
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNKelThuzad.blp",
            description={
                "+75 урона",
                "",
                "+30 к длительности \nжизни скелета",
                "+70 урона в секунду \nПрикосновение тьмы",
                "",
                "+5 регенерации маны",
                "+140 урона Зов мёртвых",
                "",
                "+3 к макс. длительности \nПрикосновение тьмы",
                "+800 здоровье скелета",
                "",
                "Похищение души без \nперезарядки",
                "-20 к перезарядки \nПрикосновение тьмы",
                "",
                "+5 зарядов Зов мёртвых",

            },
            Icons={
                "ReplaceableTextures\\CommandButtons\\BTNAttack.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNDarkSummoning.blp",
                "ReplaceableTextures\\CommandButtons\\BTNDeathCoil.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNManaStone.blp",
                "ReplaceableTextures\\CommandButtons\\BTNBansheeMaster.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNCripple.blp",
                "ReplaceableTextures\\CommandButtons\\BTNDarkSummoning.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNCripple.blp",
                "ReplaceableTextures\\CommandButtons\\BTNDeathCoil.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNBansheeMaster.blp",
            }

        },
        [20]={ -- Некрофил H00P
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNAcolyte.blp",
            description={
                "blp",
                "",
                "blp",
                "blp",
                "",
                "blp",
                "blp",
                "",
                "blp",
                "blp",
                "",
                "blp",
                "blp",
                "",
                "blp",

            },
            Icons={
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
            }

        },
        [21]={ -- Орк-чемпион H00R
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNHellScream.blp",
            description={
                "+30 урона",
                "",
                "+500 дальность \nпрыжка Прорыв",
                "-8 защиты Буйство",
                "",
                "+80 золота в минуту",
                "+150%% скорость \nатаки Бойня",
                "",
                "+350 дальности \nобзора ночью",
                "Прорыв разрушает \nдеревья",
                "",
                "+8 зарядов Чемпион",
                "Бойня союзные герои цели \nнассильно ее атакуют",
                "",
                "+50 сила",

            },
            Icons={
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
            }

        },
        [22]={ -- Паладин H00T
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNHeroPaladin.blp",
            description={
                "+200 здоровья",
                "",
                "-4 к перезарядки \nУдар по земле",
                "+5 сила",
                "",
                "+2 регенерации \nздоровья",
                "+8 защита",
                "",
                "+20\\17 лечение \nИсцеление",
                "+2 к длительности \nБожественный щит",
                "",
                "+50%% скорости атаки",
                "+2000 здоровья",
                "",
                "+50%% магического \nсопротивления",

            },
            Icons={
                "ReplaceableTextures\\CommandButtons\\BTNHealthStone.blp",
                "",
                ".ReplaceableTextures\\CommandButtons\\BTNHammer.blp",
                "UI\\Widgets\\Console\\Human\\infocard-heroattributes-str.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNHealthStone.blp",
                "ReplaceableTextures\\CommandButtons\\BTNStop.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNHolyBolt.blp",
                "ReplaceableTextures\\CommandButtons\\BTNDivineIntervention.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNAttack.blp",
                "ReplaceableTextures\\CommandButtons\\BTNHealthStone.blp",
                "",
                "UI\\Widgets\\Console\\Human\\infocard-heroattributes-int.blp",
            }

        },
        [23]={ -- Питомец вождя H00U
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNQuillBeast.blp",
            description={
                "blp",
                "",
                "blp",
                "blp",
                "",
                "blp",
                "blp",
                "",
                "blp",
                "blp",
                "",
                "blp",
                "blp",
                "",
                "blp",

            },
            Icons={
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
            }

        },
        [24]={ -- Повелитель могил H00V
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNHeroCryptLord.blp",
            description={
                "+30 урона Каннибализм",
                "",
                "+18 урона жука",
                "+80%% урона по цели \nДоминирование расы",
                "",
                "+80 скорости перемещения",
                "Каннибализм не \nтребует маны",
                "",
                "+2 к длительности \nоглушения",
                "+20%% сопротивление \nмагии",
                "",
                "Доминирование расы накладывает \nстрах на противника",
                "+120 урона",
                "",
                "+30 длительность \nжизни жука",

            },
            Icons={
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
            }

        },
        [25]={ -- Повелительница змей H00W
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNSorceress.blp",
            description={
                "+4 к длительности \nщита",
                "",
                "+1 регенерации маны",
                "+5 ко всем атрибутам",
                "",
                "-2 к перезарядки \nЗмеиная ловкость",
                "+30 урона",
                "",
                "+12 ловкости",
                "+600 дальности рывка",
                "",
                "+20%% к сопротивлению \nдлительности оглушения",
                "+50%% иммунитет к страху",
                "",
                "+420 урона от взрыва щита",

            },
            Icons={
                "ReplaceableTextures\\CommandButtons\\BTNH00WResonantImpulse.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNManaStone.blp",
                "UI\\Widgets\\Console\\Human\\infocard-heroattributes-all.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNH00WMiss.blp",
                "ReplaceableTextures\\CommandButtons\\BTNAttack.blp",
                "",
                "UI\\Widgets\\Console\\Human\\infocard-heroattributes-agi.blp",
                "ReplaceableTextures\\CommandButtons\\BTNH00WHitHide.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNEngineeringUpgrade.blp",
                "ReplaceableTextures\\CommandButtons\\BTNEngineeringUpgrade.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNH00WResonantImpulse.blp",
            }

        },
        [26]={ -- Падший рыцарь смерти H00Y
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNHeroDeathKnight.blp",
            description={
                "blp",
                "",
                "blp",
                "blp",
                "",
                "blp",
                "blp",
                "",
                "blp",
                "blp",
                "",
                "blp",
                "blp",
                "",
                "blp",

            },
            Icons={
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
            }

        },
        [27]={ -- Рыцарь смерти H00Z
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNArthasFrost.blp",
            description={
                "+30 урона",
                "",
                "+5 регенерация здоровья \nВампиризм",
                "+30 похищенного здоровья",
                "",
                "+10 сила",
                "Плеть имеет 2 заряда",
                "",
                "+15 секунд похищенного \nздоровья",
                "+500 дальность применения \nПлеть",
                "",
                "Истощение без перезарядки",
                "+6 к длительности оглушения",
                "",
                "Вампиризм становится \nпассивной способностью",

            },
            Icons={
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
            }

        },
        [28]={ -- Страж Небытия H011
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNMannoroth.blp",
            description={
                "+5 золото за убийство \nсущества",
                "",
                "+1.5 регенерация маны",
                "+4 регенерации здоровья \nНечистой ауры",
                "",
                "+300 здоровья",
                "+4 защита",
                "",
                "+200 к урону \nметеорита",
                "+12 сила",
                "",
                "+25%% скорости перемещения \nНечистой ауры",
                "Метеорит проходит сквозь \nневосприимчивость к магии",
                "",
                "-20 перезарядка \nМетеорита",

            },
            Icons={
                "UI\\Feedback\\Resources\\ResourceGold.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNManaStone.blp",
                "ReplaceableTextures\\CommandButtons\\BTNFire.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNHealthStone.blp",
                "ReplaceableTextures\\CommandButtons\\BTNStop.blp",
                "",
                "ReplaceableTextures\\PassiveButtons\\PASBTNFireRocks.blp",
                "UI\\Widgets\\Console\\Human\\infocard-heroattributes-str.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNFire.blp",
                "ReplaceableTextures\\PassiveButtons\\PASBTNFireRocks.blp",
                "",
                "ReplaceableTextures\\PassiveButtons\\PASBTNFireRocks.blp",
            }

        },
        [29]={ -- Чернокнижник H013
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNKiljaedin.blp",
            description={
                "+8 разум",
                "",
                "+20 скорости перемещения",
                "+2 регенерации здоровья",
                "",
                "+30 урона",
                "-20 к перезарядки \nГончая",
                "",
                "+8%% урон от способностей",
                "-25%% перезарядки способностей \nи предметов",
                "",
                "+500 здоровья",
                "Проклятие проходит сквозь \nневосприимчивость к магии",
                "",
                "+6 периодического \nурона Проклятие",

            },
            Icons={
                "UI\\Widgets\\Console\\Human\\infocard-heroattributes-int.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNSlippersOfAgility.blp",
                "ReplaceableTextures\\CommandButtons\\BTNHealthStone.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNAttack.blp",
                "ReplaceableTextures\\CommandButtons\\BTNPurpleFelRavager.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNEngineeringUpgrade.blp",
                "ReplaceableTextures\\CommandButtons\\BTNEngineeringUpgrade.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNHealthStone.blp",
                "ReplaceableTextures\\CommandButtons\\BTNH013TheCurse.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNH013TheCurse.blp",
            }

        },
        [30]={ -- Архитектор H030
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNSludgeFlinger.blp",
            description={
                "-4 к перезарядки",
                "",
                "+15 сожжения маны",
                "+3 регенерации маны",
                "",
                "+5 защита",
                "+2 заряда щита",
                "",
                "-1 к длительности \nоглушения",
                "-15 к перезарядки",
                "",
                "Аура работает на \nвсю карту",
                "+1600 поглощения \nмагического урона",
                "",
                "+400 урона",

            },
            Icons={
                "ReplaceableTextures\\CommandButtons\\BTNH030HealingBomb.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNH030Bubble.blp",
                "ReplaceableTextures\\CommandButtons\\BTNH030AuraMana.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNStop.blp",
                "ReplaceableTextures\\CommandButtons\\BTNH030ShieldAlive.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNH030HealingBomb.blp",
                "ReplaceableTextures\\CommandButtons\\BTNH030ShieldAlive.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNH030AuraMana.blp",
                "ReplaceableTextures\\CommandButtons\\BTNH030ShieldAlive.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNH030Bubble.blp",
            }

        },
        [31]={ -- Ведьма H03B
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNNagaSummoner.blp",
            description={
                "+5 разума",
                "",
                "+100 к дальности атаки",
                "+4 защита",
                "",
                "+2 к длительности",
                "+3 к длительности сна",
                "",
                "+175 пополнения здоровья",
                "+2 к длительности",
                "",
                "+200 скорости перемещения \nпо воде",
                "+12 регенерации маны",
                "",
                "+120 урона в секунду",

            },
            Icons={
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
            }

        },
        [32]={ -- Друид H03A
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNDruidOfTheTalon.blp",
            description={
                "+400 здоровье совы",
                "",
                "+24 урона",
                "+12%% поглощение \nмагического урона",
                "",
                "+8 к максимальной \nдлительности",
                "+1 регенерация здоровья \nза атрибут",
                "",
                "+350 маны",
                "+4 к длительности \nотравления",
                "",
                "+550 маны",
                "+24 урона в секунду",
                "",
                "+1 сова-разведчица",

            },
            Icons={
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
            }

        },
        [33]={ -- Заклинатель H02U
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNSkeletonMage.blp",
            description={
                "+50 скорости перемещения",
                "",
                "+200 дальности применения \nспособностей",
                "+8 дополнительный \nатрибут",
                "",
                "+6 к длительности",
                "+5 регенерации здоровья",
                "",
                "+157 урона",
                "+6 к длительности",
                "",
                "100%% замедление",
                "+15 разума",
                "",
                "+2 скелетов",

            },
            Icons={
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
            }

        },
        [34]={ -- Знахарь H038
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNVoljin.blp",
            description={
                "+30 урона",
                "",
                "+5 урона в секунду \nЯд",
                "-8 к перезарядки Яд",
                "",
                "+300 радиус безмолвия",
                "Яд развеивает \nположительные эффекты",
                "",
                "+500 здоровья",
                "+400 область воздействия",
                "",
                "+12%% лечения",
                "+10 атак для уничтожения",
                "",
                "Маска Вуду отталкивается от \nпротивников до четырех целей",

            },
            Icons={
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
            }

        },
        [35]={ -- Капитан H032
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNTheCaptain.blp",
            description={
                "+2 регенерация маны",
                "",
                "+30 скорости перемещения",
                "+2 заряда",
                "",
                "+18 урона в секунду",
                "+4 к длительности",
                "",
                "+8 к защите",
                "+1000 здоровья",
                "",
                "+4 защиты",
                "Огненный щит становиться \nпассивной способностью",
                "",
                "+300 здоровья и \n+30 урона за заряд",

            },
            Icons={
                "ReplaceableTextures\\CommandButtons\\BTNManaStone.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNSlippersOfAgility.blp",
                "ReplaceableTextures\\CommandButtons\\BTNH032Holy.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNH032Fireshield.blp",
                "ReplaceableTextures\\CommandButtons\\BTNH032FootmansShield.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNH032Fireshield.blp",
                "ReplaceableTextures\\CommandButtons\\BTNHealthStone.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNH032HolyShield.blp",
                "ReplaceableTextures\\CommandButtons\\BTNH032Fireshield.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNH032Holy.blp",
            }

        },
        [36]={ -- Колдун H02Y
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNOrcWarlockNecrolyte.blp",
            description={
                "+200 маны",
                "",
                "+45 золота в минуту",
                "+24 урона",
                "",
                "+140 здоровья",
                "+4 защиты",
                "",
                "+3 к длительности",
                "+32 урона",
                "",
                "+32 здоровья в секунду",
                "-50%% перезарядка способностей",
                "",
                "+20 к длительности",

            },
            Icons={
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
            }

        },
        [37]={ -- Лекарь H039
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNChaplain.blp",
            description={
                "-10 перезарядки",
                "",
                "+2 защиты",
                "+2 урона за атрибут",
                "",
                "+2%% от базового лечения",
                "+50 скорости перемещения",
                "",
                "+250 дальности луча",
                "-50 перезарядки",
                "",
                "работает по области в радиусе 600",
                "+14 длительность щита",
                "",
                "+5 длительность луча",

            },
            Icons={
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
            }

        },
        [38]={ -- Мортирный отряд H02X
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNMortarTeam.blp",
            description={
                "+6 к длительности",
                "",
                "+250 здоровья",
                "+75 урона",
                "",
                "-70 перезарядки",
                "-16 перезарядки",
                "",
                "+4 к длительности",
                "Снаряды движутся за \nкурсором",
                "",
                "+275 урона",
                "+2 заряда",
                "",
                "+1200 к максимальной \nдальности",

            },
            Icons={
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
            }

        },
        [39]={ -- Огр H02Z
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNOneHeadedOgre.blp",
            description={
                "-4 к перезарядки",
                "",
                "+4 регенерации здоровья",
                "+3 регенерации здоровья",
                "",
                "-2 к перезарядки",
                "+4 к длительности",
                "",
                "+6 к длительности",
                "+15 защита",
                "",
                "+2 длительность \nоглушения",
                "+700 дальность \nразгона",
                "",
                "+150%% скорости атаки",

            },
            Icons={
                "ReplaceableTextures\\CommandButtons\\BTNH02ZTaunt.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNHealthStone.blp",
                "ReplaceableTextures\\CommandButtons\\BTNH02ZBloodlust.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNH02ZTrample.blp",
                "ReplaceableTextures\\CommandButtons\\BTNH02ZTaunt.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNH02ZBloodlust.blp",
                "ReplaceableTextures\\CommandButtons\\BTNStop.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNH02ZRush.blp",
                "ReplaceableTextures\\CommandButtons\\BTNH02ZTrample.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNH02ZBloodlust.blp",
            }

        },
        [40]={ -- Совинный медведь H03C
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNBerserkWildKin.blp",
            description={
                "+4 длительности щита",
                "",
                "+4 регенерации здоровья",
                "+2 урона за заряд",
                "",
                "+60 урона",
                "+4 длительности змеи",
                "",
                "-6 перезарядки",
                "+8 атак для уничтожения",
                "",
                "+9%% шанса уклонения от \nспособностей",
                "+2200 дальности атаки",
                "",
                "+120 урона",

            },
            Icons={
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
            }

        },
        [41]={ -- Страж печатей H02W
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNSatyrHellcaller.blp",
            description={
                "+2 длительность астрала",
                "",
                "+30 скорости перемещения",
                "+70 урона",
                "",
                "+6 здоровья за удар",
                "+5 длительности",
                "",
                "+80 урона",
                "+4 заряда",
                "",
                "+270 урона",
                "+50 урона",
                "",
                "+400 максимальной дистанции",

            },
            Icons={
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
            }

        },
        [42]={ -- Убийца рыбаков H02V
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNMurlocNightCrawler.blp",
            description={
                "+5 ловкости",
                "",
                "+200 маны",
                "-4 перезарядки",
                "",
                "+4 защиты",
                " -8 перезарядки",
                "",
                "+30 урона",
                "+450 дальности применения",
                "",
                "+140 урона",
                "+4 удара",
                "",
                "+2 к максимальной длительности",

            },
            Icons={
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
            }

        },
        [43]={ -- Чернокнижник клана железных кулаков H031
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNHeroBloodElfPrince.blp",
            description={
                "+80 маны сожжено",
                "",
                "-12 перезарядки",
                "+7%% вампиризма",
                "",
                "+250 дальности атаки",
                "+40 урона",
                "",
                "-15%% перезарядки способностей",
                "+100 скорости перемещения",
                "",
                "+300 максимальной дистанции",
                "+16 урона в секунду",
                "",
                "перерождение после смерти перезарядка 360 секунд",

            },
            Icons={
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
                ".blp",
                "",
                ".blp",
            }

        },
        [44]={ -- Шаман H014
            Ability=SimpleID2FourCC(),
            Portrait="ReplaceableTextures\\CommandButtons\\BTNShaman.blp",
            description={
                "+200 здоровья",
                "",
                "+2 регенерации маны",
                "+180 здоровья",
                "",
                "-5 перезарядки",
                " -30 перезарядки",
                "",
                "+12 разума",
                "+4 заряда",
                "",
                "+2 к длительности",
                "+400 урона",
                "",
                "исцеляет всех союзных героев на карте",

            },
            Icons={
                "ReplaceableTextures\\CommandButtons\\BTNHealthStone.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNManaStone.blp",
                "ReplaceableTextures\\CommandButtons\\BTNSorceressMaster.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNHoldPosition.blp",
                "ReplaceableTextures\\CommandButtons\\BTNWallOfFire.blp",
                "",
                "UI\\Widgets\\Console\\Human\\infocard-heroattributes-int.blp",
                "ReplaceableTextures\\CommandButtons\\BTNSorceressMaster.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNHoldPosition.blp",
                "ReplaceableTextures\\CommandButtons\\BTNWallOfFire.blp",
                "",
                "ReplaceableTextures\\CommandButtons\\BTNSorceressMaster.blp",
            }

        },
        [45]={
            Ability=SimpleID2FourCC(),
            Portrait="",
            description={},
            Icons={}
        },
        [46]={
            Ability=SimpleID2FourCC(),
            Portrait="",
            description={},
            Icons={}
        },
        [47]={
            Ability=SimpleID2FourCC(),
            Portrait="",
            description={},
            Icons={}
        },
        [48]={
            Ability=SimpleID2FourCC(),
            Portrait="",
            description={},
            Icons={}
        },
        [49]={
            Ability=SimpleID2FourCC(),
            Portrait="",
            description={},
            Icons={}
        },
        [50]={
            Ability=SimpleID2FourCC(),
            Portrait="",
            description={},
            Icons={}
        },
        [51]={
            Ability=SimpleID2FourCC(),
            Portrait="",
            description={},
            Icons={}
        },
        [52]={
            Ability=SimpleID2FourCC(),
            Portrait="",
            description={},
            Icons={}
        },
        [53]={
            Ability=SimpleID2FourCC(),
            Portrait="",
            description={},
            Icons={}
        },
    }
end
function GetHeroIndexInTable(HeroID)
    local table={}
    table[FourCC('H00S')]=1 -- падший король R
    table[FourCC('H00X')]=2 -- провидец пустоты R
    table[FourCC('H012')]=3 -- хранитель сада R
    table[FourCC('H00Q')]=4 -- несущий огонь R
    table[FourCC('H00H')]=5 -- королева бездны R
    table[FourCC('H00J')]=6 -- ледяная виверна R
    table[FourCC('H007')]=7 -- архикрыса R
    table[FourCC('H008')]=8 -- вампир R
    table[FourCC('H009')]=9 -- вождь троллей R
    table[FourCC('H00A')]=10 -- волшебница R
    table[FourCC('H00B')]=11 -- вурдалак
    table[FourCC('H00D')]=12 -- госпожа средних миров
    table[FourCC('H00F')]=13 -- дух пространства
    table[FourCC('H00G')]=14 -- копатель
    table[FourCC('H00I')]=15 -- крыса
    table[FourCC('H00K')]=16 -- ловец духов
    table[FourCC('H00M')]=17 -- мать пауков
    table[FourCC('H00N')]=18 -- молотобоец
    table[FourCC('H00O')]=19 -- некромант
    table[FourCC('H00P')]=20 -- некрофил
    table[FourCC('H00R')]=21 -- орк-чемпион
    table[FourCC('H00T')]=22 -- паладин
    table[FourCC('H00U')]=23 -- питомец вождя
    table[FourCC('H00V')]=24 -- повелитель могил
    table[FourCC('H00W')]=25 -- повелительница змей
    table[FourCC('H00Y')]=26 -- падший рыцарь смерти
    table[FourCC('H00Z')]=27 -- рыцарь смерти
    table[FourCC('H011')]=28 -- страж небытия
    table[FourCC('H013')]=29 -- чернокнижник
    table[FourCC('H030')]=30 -- архитектор
    table[FourCC('H03B')]=31 -- ведьма
    table[FourCC('H03A')]=32 -- друид
    table[FourCC('H02U')]=33 -- заклинатель
    table[FourCC('H038')]=34 -- знахарь
    table[FourCC('H032')]=35 -- капитан
    table[FourCC('H02Y')]=36 -- колдун
    table[FourCC('H039')]=37 -- лекарь
    table[FourCC('H02X')]=38 -- мортирный отряд
    table[FourCC('H02Z')]=39 -- огр
    table[FourCC('H03C')]=40 -- совинный знахарь
    table[FourCC('H02W')]=41 -- страж печатей
    table[FourCC('H02V')]=42 -- убийца рыбаков
    table[FourCC('H031')]=43 -- чернокнижник клана железных кулаков
    table[FourCC('H014')]=44 -- шаман
    table[FourCC('H00E')]=45 -- архонт
    table[FourCC('H00C')]=46 -- победитель бездны
    table[FourCC('H00L')]=47 -- хранитель морей
    table[FourCC('H006')]=48 -- часовой
    table[FourCC('H010')]=49 -- алхимик

    if not table[HeroID] then
        table[HeroID]=nil
        --print("Герой так и не был найден в базе данных")
    end
    return table[HeroID]
end