---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 10.07.2020 0:37
---
---

--[[do --Инициализация
	TimerStart(CreateTimer(), 0.1, false, function()
		if BlzLoadTOCFile("SystemGeneric\\Main.toc") then
			--print("успех")
		else
			print("провал загрузки ТОС ")
		end
	end)
end]]

FrameStep=0.039
local TalentTable={}
function CreateTalentButton(pid)
	TalentTable[pid]={
		miniTalentTable={}
	}
	local data=TalentTable[pid]
	-- наведение на глюбаттон гооврит что это таланты
	-- глик по фрейму учит талант, если есть свободное очко

	local next = FrameStep
	local buttonFrame = BlzCreateFrameByType("GLUEBUTTON", "FaceButton", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "IconButtonTemplate", 0)
	local buttonIconFrame = BlzCreateFrameByType("BACKDROP", "FaceButtonIcon", buttonFrame, "", 0)
	BlzFrameSetAllPoints(buttonIconFrame, buttonFrame)
	BlzFrameSetTexture(buttonIconFrame, "ReplaceableTextures\\CommandButtons\\BTNSelectHeroOn", 0, true)
	BlzFrameSetAbsPoint(buttonFrame, FRAMEPOINT_LEFT, 0, 0.4)
	BlzFrameSetSize(buttonFrame, next, next * 2.5)
	local tree=CreateTalentTree(buttonFrame,pid) --TODO Сюда игрока передать

	local ClickTrig = CreateTrigger()
	BlzTriggerRegisterFrameEvent(ClickTrig, buttonFrame, FRAMEEVENT_CONTROL_CLICK)
	local showState=false
	TriggerAddAction(ClickTrig, function()
		--print("Нажата кнопка ")
		BlzFrameSetEnable(BlzGetTriggerFrame(), false)
		BlzFrameSetEnable(BlzGetTriggerFrame(), true)
		if not showState then
			ShowTalentTree(tree,true)
			showState=true
		else
			ShowTalentTree(tree,false)
			showState=false
		end
	end)
	local TrigMOUSE_ENTER = CreateTrigger()
	BlzTriggerRegisterFrameEvent(TrigMOUSE_ENTER, buttonFrame, FRAMEEVENT_MOUSE_ENTER)
	TriggerAddAction(TrigMOUSE_ENTER, function()
		--print("показать подсказку")
	end)
	local TrigMOUSE_LEAVE = CreateTrigger()
	BlzTriggerRegisterFrameEvent(TrigMOUSE_LEAVE, buttonFrame, FRAMEEVENT_MOUSE_LEAVE)
	TriggerAddAction(TrigMOUSE_LEAVE, function()
		--print("убрать подсказку")
	end)
	local k = 0
	local m = 0

	for i = 1, 10 do
		local miniTalent = BlzCreateFrameByType("BACKDROP", "Face", buttonFrame, "", 0)
		data.miniTalentTable[i]=miniTalent
		BlzFrameSetTexture(miniTalent, "ReplaceableTextures\\CommandButtons\\BTNSelectHeroOn", 0, true)
		--BlzFrameSetAlpha(cd, 128)
		BlzFrameSetSize(miniTalent, next / 2, next / 2)

		if k == 5 then
			m = 1
			k = 0
		end
		k = k + 1
		BlzFrameSetPoint(miniTalent, FRAMEPOINT_BOTTOMLEFT, buttonFrame, FRAMEPOINT_BOTTOMLEFT, 0 + m * (next / 2), 0 + (k - 1) * (next / 2))
	end
end

function CreateTalentTree(buttonFrame,pid)

	-- заголовок
	-- текстблоки глюбаттоны 3 на 5
	local data=TalentTable[pid]
	local next = FrameStep
	local tree={}
	tree[pid]={
		left={},
		middle={},
		right={}
	}
	for i = 1, 5 do
		local mainButton = BlzCreateFrame("ScriptDialogButton", buttonFrame, 0, 0)
		BlzFrameSetSize(mainButton, next*3, next)
		BlzFrameSetPoint(mainButton, FRAMEPOINT_RIGHT, buttonFrame,FRAMEPOINT_RIGHT,next*3, 0-next*2+((i-1)*next))
		BlzFrameSetText(mainButton, "Левый талант "..i)
		BlzFrameSetVisible(mainButton,false)
		tree[pid].left[i]=mainButton

		local trig = CreateTrigger()
		BlzTriggerRegisterFrameEvent(trig, mainButton, FRAMEEVENT_CONTROL_CLICK)
		TriggerAddAction(trig, function()
			print("выбран этот левый талант "..i)


			BlzFrameSetTexture(data.miniTalentTable[i], "", 0, true)

			BlzFrameSetEnable(mainButton,false)
			BlzFrameSetEnable(tree[pid].right[i],false)
		end)
	end

	local lvl={5,15,20,25,30}
	for i = 1, 5 do
		local mainButton = BlzCreateFrame("ScriptDialogButton", buttonFrame, 0, 0)
		BlzFrameSetSize(mainButton, next, next)
		BlzFrameSetPoint(mainButton, FRAMEPOINT_RIGHT, buttonFrame,FRAMEPOINT_RIGHT,next*4, 0-next*2+((i-1)*next))
		BlzFrameSetText(mainButton, lvl[i])
		BlzFrameSetEnable(mainButton,false)
		BlzFrameSetVisible(mainButton,false)
		tree[pid].middle[i]=mainButton
	end


	for i = 1, 5 do
		local mainButton = BlzCreateFrame("ScriptDialogButton", buttonFrame, 0, 0)
		BlzFrameSetSize(mainButton, next*3, next)
		BlzFrameSetPoint(mainButton, FRAMEPOINT_RIGHT, buttonFrame,FRAMEPOINT_RIGHT,next*7, 0-next*2+((i-1)*next))
		BlzFrameSetText(mainButton, "Правый талант "..i)
		BlzFrameSetVisible(mainButton,false)
		tree[pid].right[i]=mainButton
		local trig = CreateTrigger()
		BlzTriggerRegisterFrameEvent(trig, mainButton, FRAMEEVENT_CONTROL_CLICK)
		TriggerAddAction(trig, function()
			print("выбран этот правый талант "..i)
			BlzFrameSetTexture(data.miniTalentTable[i+5], "", 0, true)
			BlzFrameSetEnable(mainButton,false)
			BlzFrameSetEnable(tree[pid].left[i],false)
		end)
	end
	return tree[pid]
end

function ShowTalentTree(tree,show)
	for k=1,3 do
		for i=1,5 do
			if k==1 then
				BlzFrameSetVisible(tree.left[i],show)
			end
			if k==2 then
				BlzFrameSetVisible(tree.middle[i],show)
			end
			if k==3 then
				BlzFrameSetVisible(tree.right[i],show)
			end
		end
	end
end