---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 04.06.2020 14:02
---
function HealthBarAdd(data,color)
	BlzLoadTOCFile("SystemGeneric\\Main.toc")
	local bar = BlzCreateSimpleFrame("MyFakeBar", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), 0)
	BlzFrameSetVisible(bar,false)
	local xBar=0.189
	if color==1 then xBar=0.365 end

	if GetPlayerId(GetLocalPlayer())==data.pid  then -- хп бары, они точно в норме
		BlzFrameSetVisible(bar,true)
	end
	BlzFrameSetTexture(bar, "Replaceabletextures\\Teamcolor\\Teamcolor0"..color..".blp", 0, true)-- 0 красный
	BlzFrameSetTexture(BlzGetFrameByName("MyFakeBarBorder",0),"SystemGeneric\\MyBarBorder.blp", 0, true)
	BlzFrameSetText(BlzGetFrameByName("MyFakeBarTitle",0), "")--‡ Сердце ™ щит
	local lefttext = BlzGetFrameByName("MyFakeBarLeftText",0)
	local righttext = BlzGetFrameByName("MyFakeBarRightText",0)
	local function on_timer()
		--print("update")
		if color==0 then
			BlzFrameSetValue(bar, GetUnitLifePercent(data.SelectedHero))
			BlzFrameSetText(lefttext, R2I(GetWidgetLife(data.SelectedHero)))
			BlzFrameSetText(righttext, BlzGetUnitRealField(data.SelectedHero,UNIT_RF_HIT_POINTS_REGENERATION_RATE))

		end
		if color==1 then
			BlzFrameSetValue(bar, GetUnitManaPercent(data.SelectedHero))
			BlzFrameSetText(lefttext, R2I(GetUnitState(data.SelectedHero,UNIT_STATE_MANA)))
			BlzFrameSetText(righttext, BlzGetUnitRealField(data.SelectedHero,UNIT_RF_MANA_REGENERATION))
		end

	end
	TimerStart(CreateTimer(),0.5,true, on_timer)

	BlzFrameSetAbsPoint(bar, FRAMEPOINT_LEFT, xBar, 0.072)
	BlzFrameSetSize(bar,.175,.015)

end