---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 16.05.2020 21:22
---
---
---

function HideEverythingOld()
	BlzHideOriginFrames(true)
	BlzEnableUIAutoPosition ( false )
	local GAME_UI     = BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0)
	local WORLD_FRAME = BlzGetOriginFrame(ORIGIN_FRAME_WORLD_FRAME, 0)
	BlzFrameSetAllPoints(WORLD_FRAME, GAME_UI)
	BlzFrameSetAlpha(BlzGetFrameByName("SimpleInventoryCover", 0), 0)
	BlzFrameSetVisible(BlzFrameGetParent(BlzGetOriginFrame(ORIGIN_FRAME_ITEM_BUTTON, 0)), true)
	BlzFrameSetVisible(BlzGetOriginFrame(ORIGIN_FRAME_HERO_BAR,0), false)
	BlzFrameSetVisible(BlzGetFrameByName("ResourceBarFrame",0),true)
	BlzFrameSetScale(BlzFrameGetChild(BlzGetFrameByName("ConsoleUI",0),5), 0.001)
	--BlzFrameSetAbsPoint(BlzGetOriginFrame(ORIGIN_FRAME_CHAT_MSG, 0), FRAMEPOINT_BOTTOMLEFT, 0.1 ,0.15)
	--BlzFrameSetAbsPoint(BlzGetOriginFrame(ORIGIN_FRAME_UNIT_MSG, 0), FRAMEPOINT_BOTTOMLEFT, 0.15 ,0.2)
	local fps=BlzGetFrameByName("ResourceBarFrame",0)
	BlzFrameClearAllPoints(fps)
	BlzFrameSetAbsPoint(fps, FRAMEPOINT_CENTER, 0.9 ,0.61)
	local infoPanel=BlzFrameGetParent(BlzGetFrameByName("SimpleInfoPanelUnitDetail",0)) -- панель стат героя
	BlzFrameClearAllPoints(infoPanel)
    BlzFrameSetVisible(infoPanel,true)
	BlzFrameSetAbsPoint(infoPanel, FRAMEPOINT_CENTER, 0,9) --0,9 чтобы полностью убрать


	--BlzFrameSetSize(infoPanel, 0.05, 0.05)
	--убираем всю инфопанель кроме статуса
	--[[
	BlzFrameSetAbsPoint(BlzGetFrameByName("InfoPanelIconHeroStrengthLabel",6), FRAMEPOINT_CENTER, 0.9 ,5)
	BlzFrameSetAbsPoint(BlzGetFrameByName("InfoPanelIconHeroStrengthValue",6), FRAMEPOINT_CENTER, 0.9 ,5)
	BlzFrameSetAbsPoint(BlzGetFrameByName("InfoPanelIconHeroIntellectLabel",6), FRAMEPOINT_CENTER, 0.9 ,5)
	BlzFrameSetAbsPoint(BlzGetFrameByName("InfoPanelIconHeroIntellectValue",6), FRAMEPOINT_CENTER, 0.9 ,5)
	BlzFrameSetAbsPoint(BlzGetFrameByName("InfoPanelIconHeroAgilityLabel",6), FRAMEPOINT_CENTER, 0.9 ,5)
	BlzFrameSetAbsPoint(BlzGetFrameByName("InfoPanelIconHeroAgilityValue",6), FRAMEPOINT_CENTER, 0.9 ,5)
	BlzFrameSetAbsPoint(BlzGetFrameByName("InfoPanelIconBackdrop",0), FRAMEPOINT_CENTER, 0.9 ,0.9)
	BlzFrameSetAbsPoint(BlzGetFrameByName("InfoPanelIconBackdrop",1), FRAMEPOINT_CENTER, 0.9 ,0.9)
	BlzFrameSetAbsPoint(BlzGetFrameByName("InfoPanelIconBackdrop",2), FRAMEPOINT_CENTER, 0.9 ,0.9)
	BlzFrameSetAbsPoint(BlzGetFrameByName("InfoPanelIconBackdrop",3), FRAMEPOINT_CENTER, 0.9 ,0.9)
	BlzFrameSetAbsPoint(BlzGetFrameByName("InfoPanelIconBackdrop",4), FRAMEPOINT_CENTER, 0.9 ,0.9)
	BlzFrameSetAbsPoint(BlzGetFrameByName("InfoPanelIconBackdrop",5), FRAMEPOINT_CENTER, 0.9 ,0.9)
	]]





	BlzFrameClearAllPoints(BlzGetOriginFrame(ORIGIN_FRAME_UBERTOOLTIP, 0)) -- ПОдсказка при наведении на дефолт фреймы
	BlzFrameSetPoint(BlzGetOriginFrame(ORIGIN_FRAME_UBERTOOLTIP, 0), FRAMEPOINT_BOTTOM, BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), FRAMEPOINT_BOTTOM, 0, 0.13)


	for i = 0,11 do --отвязка всех кнопок
		--print("очистка.. "..i)
		BlzFrameClearAllPoints(BlzGetFrameByName("CommandButton_"..i, 0))
		BlzFrameSetAbsPoint(BlzGetFrameByName("CommandButton_"..i, 0),FRAMEPOINT_CENTER,1,1)
		--
	end
--[[

	for i=0,2 do --QWE
		BlzFrameSetAbsPoint(BlzGetFrameByName("CommandButton_"..i+8, 0), FRAMEPOINT_CENTER, 0.2065+next*i ,(next*2)-0.005)
	end
	for i=0,2 do --RTY
		BlzFrameSetAbsPoint(BlzGetFrameByName("CommandButton_"..i+5, 0), FRAMEPOINT_CENTER, 0.2065+next*i ,(next*1)-0.005)
	end
]]


	local black=ResizeBlackPanel()
	Resources()
	MenuFrame()
	ShowMap()
	ShowPortraitFrame(black)
	ShowInventory(black)
	CreateQWERDFG()

end

function CreateInterface()
	local Back= BlzCreateFrameByType("BACKDROP", "Face", BlzGetOriginFrame(ORIGIN_FRAME_WORLD_FRAME, 0), "", 0)
	BlzFrameSetTexture(Back, "InterfaceKodumMain", 0, true)
	BlzFrameSetSize(Back, 0.52, 0.525)
	BlzFrameSetAbsPoint(Back, FRAMEPOINT_CENTER,0.4 , 0.26)
end


function Resources()
	local GoldIcon =BlzCreateFrameByType("BACKDROP", "Face", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0)

	-- BlzCreateFrame('Steel-Backdrop', BlzGetOriginFrame(ORIGIN_FRAME_WORLD_FRAME, 0), 0, 0)

	BlzFrameSetTexture(GoldIcon, 'UI/Widgets/ToolTips/Human/ToolTipGoldIcon.blp', 0, true)
	BlzFrameSetSize(GoldIcon, 0.018, 0.018)
	BlzFrameClearAllPoints(GoldIcon)
	BlzFrameSetAbsPoint(GoldIcon, FRAMEPOINT_CENTER, 0.78 ,0.55)
	--BlzFrameSetPoint(GoldIcon, FRAMEPOINT_RIGHT, InfoBackdrop, FRAMEPOINT_RIGHT, -0.038, 0.008)

	local GoldText = BlzGetFrameByName('ResourceBarGoldText', 0)
	BlzFrameClearAllPoints(GoldText)
	BlzFrameSetPoint(GoldText, FRAMEPOINT_CENTER, GoldIcon, FRAMEPOINT_CENTER, 0, 0)

	local LumberIcon = BlzCreateFrameByType("BACKDROP", "Face", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0)
	BlzFrameSetTexture(LumberIcon, 'UI/Widgets/ToolTips/Human/ToolTipStonesIcon.blp', 0, true)
	BlzFrameSetSize(LumberIcon, 0.018, 0.018)
	BlzFrameSetAbsPoint(LumberIcon, FRAMEPOINT_CENTER, 0.78 ,0.53)
	--BlzFrameSetPoint(LumberIcon, FRAMEPOINT_RIGHT, InfoBackdrop, FRAMEPOINT_RIGHT, -0.038, -0.008)

	local LumberText = BlzGetFrameByName('ResourceBarLumberText', 0)
	BlzFrameClearAllPoints(LumberText)
	BlzFrameSetPoint(LumberText, FRAMEPOINT_CENTER, LumberIcon, FRAMEPOINT_CENTER, 0, 0)
end

function MenuFrame()
	BlzFrameSetVisible(BlzGetFrameByName("UpperButtonBarFrame",0),true)
	for i=0,3 do
		local f10=BlzGetOriginFrame(ORIGIN_FRAME_SYSTEM_BUTTON, i)
		BlzFrameSetVisible(f10, true) --не не работает
		BlzFrameClearAllPoints(f10)
		BlzFrameSetAbsPoint(f10, FRAMEPOINT_CENTER, 0.00+(0.08*i) ,0.59)
	end
end

function ShowPortraitFrame(black)
	local portrait=BlzGetOriginFrame(ORIGIN_FRAME_PORTRAIT, 0)
	BlzFrameClearAllPoints(portrait)
	BlzFrameSetVisible(portrait, true)
	--BlzFrameSetAbsPoint(portrait, FRAMEPOINT_CENTER, 0.025 ,0.025)
	BlzFrameSetSize(portrait,0.05,0.05)
	BlzFrameSetPoint(portrait,FRAMEPOINT_LEFT,black,FRAMEPOINT_LEFT,0.088,0.015)
end

function ShowMap()
	local map=BlzGetOriginFrame(ORIGIN_FRAME_MINIMAP, 0)
	BlzFrameClearAllPoints(map)
	BlzFrameSetVisible(map, false)
	BlzFrameSetAbsPoint(map, FRAMEPOINT_CENTER, 0.7 ,0.05)
	BlzFrameSetSize(map,0.1,.1)
end

function ShowInventory(black)
	local next=0.039
	local step=(next*6)+next/2
	for i = 0, 5 do
		local item = BlzGetOriginFrame(ORIGIN_FRAME_ITEM_BUTTON, i)
		BlzFrameSetVisible(item, true)
		BlzFrameClearAllPoints(item)
		BlzFrameSetSize(item, next, next)
		if i>=3 then
			BlzFrameSetPoint(item,FRAMEPOINT_BOTTOM,black,FRAMEPOINT_BOTTOM,step-(next*3)+next*i,0)
			--BlzFrameSetAbsPoint(item, FRAMEPOINT_CENTER, 0.515-(next*3)+next*i ,(next*1)-0.005)
		else
			BlzFrameSetPoint(item,FRAMEPOINT_BOTTOM,black,FRAMEPOINT_BOTTOM,step+(next*i),next)
			--BlzFrameSetAbsPoint(item, FRAMEPOINT_CENTER, 0.515+(next*i) ,next*2)-0.005)
		end
	end
end

function CreateQWERDFG()
	local next=0.039
	for i=0,8 do --RTY
		BlzFrameSetAbsPoint(BlzGetFrameByName("CommandButton_"..i, 0), FRAMEPOINT_CENTER, 0.2065+next*i ,(next*1)+next/8)
	end
end

function ResizeBlackPanel()
	local black=BlzGetFrameByName("ConsoleUIBackdrop", 0)
	BlzFrameSetVisible(black, true)
	BlzFrameClearAllPoints(black)
	BlzFrameSetSize(black,0.7,0.04*2)
	BlzFrameSetPoint(black,FRAMEPOINT_BOTTOM,BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0),FRAMEPOINT_BOTTOM,0,0)
	return black
end

