---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 18.10.2020 12:01
---

do --Инициализация
	TimerStart(CreateTimer(), 0.1, false, function()
		InitSelectionRegister()
	end)
end

function InitSelectionRegister()
	local this = CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		TriggerRegisterPlayerUnitEvent(this, Player(i), EVENT_PLAYER_UNIT_SELECTED, nil)
	end
	TriggerAddAction(this, function()
		local hero=GetTriggerUnit()
		--print(GetUnitName(hero))
		if IsUnitType(hero,UNIT_TYPE_HERO)   then
			local data=HERO[GetPlayerId(GetTriggerPlayer())]
			if GetOwningPlayer(hero)==GetTriggerPlayer()  then


				--UnitDisableAllPassAbilityTimed(hero,2)
				--UnitTestMS(hero)
				if not data.UnitHero then
					data.UnitHero=hero
					--print("Определён первый герой для игрока, для которого и будут СОЗДАНЫ таланты")
					CreateTalonButtons(data)
				else
					if hero==data.UnitHero then
						print("повтроное отображение талантов")
					else
						print("очистка дерева талантов, выбран другой герой")
					end
				end
			else
				print("очистка дерева талантов, выбран другой герой")
			end
			data.SelectedHero=hero
		end
	end)
end


function CreateTalonButtons(data)
	local hero=data.UnitHero
	local step=0.039/1.5
	local indexHero=GetHeroIndexInTable(GetUnitTypeId(hero))
	data.indexHero=indexHero
	--print(indexHero)
	data.TalonTable={
		self=nil,
		learnBox=nil,
		tooltip=nil,
		tooltipText=nil,
		arrayButtons={},
		learnedButtons={},
		status={},
		currentLearned=0,
		show=false
	}
	data.TalonTable.self=CreateSimpleFrameGlue(BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0),0.22,0.15,step,nil,1,nil,data)
	data.TalonTable.learnBox = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', data.TalonTable.self, '', 0)

	--СОздаём сам таланты
	local sx,sy=0.1,0.18
	local k=1
	local lvl={5,15,20,25,30}
	for j=0,4 do
		for i=0,2 do
			if k==2 or k==5 or k==8 or k==11 or k==14 then
				--созданий цирф без кликабельности
				data.TalonTable.arrayButtons[k]=CreateSimpleFrameGlue(data.TalonTable.learnBox,sx+step*i,sy+step*j,step,"SystemGeneric\\UI\\FrameBlack.dds",nil,lvl[j+1])

			else
				-- cами таланты кликабельные
				data.TalonTable.arrayButtons[k]=CreateSimpleFrameGlue(data.TalonTable.learnBox,sx+step*i,sy+step*j,step,TalonBD[indexHero].Icons[k],1,nil,data,k)
				data.TalonTable.status[k]=true
			end
			k=k+1
		end
	end
	-- Создаём тултип
	data.TalonTable.tooltip,_,data.TalonTable.tooltipText=CreateToolTipBox(data.TalonTable.self,0.23,0.25)
	--Заздаём сетку из изученных полей
	--k=1
	--sx,sy=0.1,0.18

	--data.TalonTable.learnedButtons[k]=CreateSimpleFrameGlue(data.TalonTable.learnBox,sx+step*i,sy,step,TalonBD[indexHero].Icons[k],nil,lvl[j+1])
	ShowTalonTree(data,false)
end



function CreateSimpleFrameGlue(parent,posX, PosY,scale,texture, flag,text,data,k)
	if not texture then
		texture = "ReplaceableTextures\\CommandButtons\\BTNSelectHeroOn"
	end
	local SelfFrame = BlzCreateFrameByType('GLUEBUTTON', 'FaceButton', parent, 'ScoreScreenTabButtonTemplate', 0)
	local buttonIconFrame = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', SelfFrame, '', 0)
	--BlzFrameSetVisible(SelfFrame, false)
	-- BlzFrameSetVisible(SelfFrame, GetLocalPlayer() == player)
	BlzFrameSetAllPoints(buttonIconFrame, SelfFrame)
	BlzFrameSetTexture(buttonIconFrame, texture, 0, true)
	BlzFrameSetSize(SelfFrame, scale, scale)
	BlzFrameSetAbsPoint(SelfFrame, FRAMEPOINT_CENTER, posX, PosY)

	if flag ==1 then
		local ClickTrig = CreateTrigger()
		BlzTriggerRegisterFrameEvent(ClickTrig, SelfFrame, FRAMEEVENT_CONTROL_CLICK)
		TriggerAddAction(ClickTrig, function()
			--print("Нажата кнопка ")
			BlzFrameSetEnable(BlzGetTriggerFrame(), false)
			BlzFrameSetEnable(BlzGetTriggerFrame(), true)
			if not k then
				--print("открываем меню талантов")
				if not data.TalonTable.show then
					data.TalonTable.show=true
					ShowTalonTree(data,true)
				else
					data.TalonTable.show=false
					ShowTalonTree(data,false)
				end
			end


			if  data.TalonTable.status[k]  then
				if k then
					DisabledAnotherTalon(data,k)
					AddTalonToLearned(data,k)
				else -- клик для меню талантов

				end
			else
				--print("Эти таланты уже изучены")
			end
		end)

		local TrigMOUSE_ENTER = CreateTrigger()
		BlzTriggerRegisterFrameEvent(TrigMOUSE_ENTER, SelfFrame, FRAMEEVENT_MOUSE_ENTER)

		TriggerAddAction(TrigMOUSE_ENTER, function()
			--print("показать подсказку "..flag)
			BlzFrameSetVisible(data.TalonTable.tooltip,true)
			if k then
				BlzFrameSetText(data.TalonTable.tooltipText,TalonBD[data.indexHero].description[k])
				BlzFrameSetAbsPoint(data.TalonTable.tooltip, FRAMEPOINT_CENTER, 0.23,PosY)
			else
				BlzFrameSetText(data.TalonTable.tooltipText,"Открывает доступ \nк меню талантов")
				BlzFrameSetAbsPoint(data.TalonTable.tooltip, FRAMEPOINT_CENTER, 0.23,PosY+0.05)
			end
			--print(#TalonBD[data.indexHero].description[k])

			--mouseOnFrame=true

		end)
		local TrigMOUSE_LEAVE = CreateTrigger()
		BlzTriggerRegisterFrameEvent(TrigMOUSE_LEAVE, SelfFrame, FRAMEEVENT_MOUSE_LEAVE)
		TriggerAddAction(TrigMOUSE_LEAVE, function()
			--print("убрать подсказку")
			BlzFrameSetVisible(data.TalonTable.tooltip,false)
			--mouseOnFrame=false

		end)
	else --пассивная кнопка без событий

	end

	if flag==2 then -- только подсказка
		local TrigMOUSE_ENTER = CreateTrigger()
		BlzTriggerRegisterFrameEvent(TrigMOUSE_ENTER, SelfFrame, FRAMEEVENT_MOUSE_ENTER)

		TriggerAddAction(TrigMOUSE_ENTER, function()
			--print("показать подсказку "..flag)
			BlzFrameSetVisible(data.TalonTable.tooltip,true)
			BlzFrameSetText(data.TalonTable.tooltipText,TalonBD[data.indexHero].description[k])
			--print(#TalonBD[data.indexHero].description[k])
			BlzFrameSetAbsPoint(data.TalonTable.tooltip, FRAMEPOINT_CENTER, posX,0.2)


		end)
		local TrigMOUSE_LEAVE = CreateTrigger()
		BlzTriggerRegisterFrameEvent(TrigMOUSE_LEAVE, SelfFrame, FRAMEEVENT_MOUSE_LEAVE)
		TriggerAddAction(TrigMOUSE_LEAVE, function()
			--print("убрать подсказку")
			BlzFrameSetVisible(data.TalonTable.tooltip,false)
			--mouseOnFrame=false

		end)
	end

	if text then
		local info = BlzCreateFrameByType("TEXT", "ButtonChargesText", SelfFrame, "", 0)
		BlzFrameSetText(info,text)
		BlzFrameSetPoint(info, FRAMEPOINT_CENTER, SelfFrame, FRAMEPOINT_CENTER, 0.0, 0.0)
		BlzFrameSetScale(info,2)
	end
	return SelfFrame
end





mouseOnFrame=false
--mainTooltip=nil
function CreateToolTipBox(parent,posX,posY)
	local tooltip = BlzCreateFrameByType("FRAME", "TestDialog", parent, "StandardFrameTemplate", 0)
	local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", tooltip, "", 0)
	local backdrop = BlzCreateFrame("QuestButtonDisabledBackdropTemplate", tooltip, 0, 0)
	BlzFrameSetAbsPoint(tooltip, FRAMEPOINT_CENTER, posX,posY)
	BlzFrameSetSize(tooltip, 0.12, 0.04)
	BlzFrameSetSize(backdrop, 0.12, 0.04)
	BlzFrameSetPoint(backdrop, FRAMEPOINT_CENTER, tooltip, FRAMEPOINT_CENTER, 0.0, 0.0)
	BlzFrameSetAlpha(backdrop,200)
	--BlzFrameSetAlpha(text,255)
	BlzFrameSetText(text,"Первичный текст")
	--BlzFrameSetPoint(text, FRAMEPOINT_CENTER, tooltip, FRAMEPOINT_CENTER, 0.0, 0.0)
	BlzFrameSetPoint(text, FRAMEPOINT_TOPLEFT, tooltip, FRAMEPOINT_TOPLEFT, 0.01, -0.01)
	BlzFrameSetVisible(tooltip,false)
	return tooltip,backdrop,text
end

do -- BD
	TalonBD={
		[1]={ --Падший король H00S
			description={
				"+2 регенерации маны",
				"",
				"+20 урона",
				"+75 к урону от \nмолний",
				"",
				"+8 к силе",
				"+100 к сильному \nудару",
				"",
				"Цепь молний без \nперезарядки",
				"+18 процентов шанса\n удар молнии",
				"",
				"+50 скорости \nперемещения",
				"-50 сек перезарядки \nпробуждения",
				"",
				"Сильный удар \nстановится пассивным",

			},
			Icons={
				"ReplaceableTextures\\CommandButtons\\BTNSobiMask.blp",
				"",
				"ReplaceableTextures\\CommandButtons\\BTNClawsOfAttack.blp",
				"ReplaceableTextures\\CommandButtons\\BTNOrbOfLightning.blp",
				"",
				"ReplaceableTextures\\CommandButtons\\BTNGauntletsOfOgrePower.blp",
				"ReplaceableTextures\\CommandButtons\\BTNBash.blp",
				"",
				"ReplaceableTextures\\CommandButtons\\BTNChainLightning.blp",
				"ReplaceableTextures\\CommandButtons\\BTNChainLightning.blp",
				"",
				"ReplaceableTextures\\CommandButtons\\BTNBootsOfSpeed.blp",
				"ReplaceableTextures\\CommandButtons\\BTNAvatarOn.blp",
				"",
				"ReplaceableTextures\\PassiveButtons\\PASBTNBash.blp",
			}
		},
		[2]={ -- другой герой
			description={
				-- описания
			},
			Icons={
				--пути для иконок
			}
		},
	}
end
function GetHeroIndexInTable(HeroID)
	local table={}
	table[FourCC('H00S')]=1

	if not table[HeroID] then
		print("Герой так и не был найден в базе данных")
	end
	return table[HeroID]
end

function DisabledAnotherTalon(data,k)
	local b=0
	local c=0
	if k==1 then b=3 c=2
	elseif k==3 then b=1 c=2

	elseif k==4 then b=6 c=5
	elseif k==6 then b=4 c=5

	elseif k==7 then b=9 c=8
	elseif k==9 then b=7 c=8

	elseif k==10 then b=12 c=11
	elseif k==12 then b=10 c=11

	elseif k==13 then b=15 c=14
	elseif k==15 then b=13 c=14
	end
	--print(" изучен талант "..k.." и будет заблокирован "..b)
	data.TalonTable.status[b]=false
	data.TalonTable.status[k]=false
	BlzFrameSetAlpha(data.TalonTable.arrayButtons[k],50)
	BlzFrameSetAlpha(data.TalonTable.arrayButtons[b],50)
	BlzFrameSetAlpha(data.TalonTable.arrayButtons[c],50)
end

function AddTalonToLearned(data,k)
	--k=1
	local sx,sy=0.26,0.15
	local step=0.039/1.5

	data.TalonTable.learnedButtons[k]=CreateSimpleFrameGlue(data.TalonTable.self,sx+step*data.TalonTable.currentLearned,sy,step,TalonBD[data.indexHero].Icons[k],2,nil,data,k)
	data.TalonTable.currentLearned=data.TalonTable.currentLearned+1
end

function ShowTalonTree(data,state)
	BlzFrameSetVisible(data.TalonTable.learnBox,state)
end