---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 19.10.2020 21:40
---

do --Инициализация
    TimerStart(CreateTimer(), 0.1, false, function()
        CreatePickTable()
    end)
end

function CreatePickTable()
    HideEverything() -- скрываем всё
    --CreateBlackTip() -- создаём внешнюю рамку
    CreateAllHeroID() -- создаём болванчиков
    CreateAllHeroInBox(10)
end


function HideEverything()
    BlzFrameSetVisible(BlzGetFrameByName("ConsoleUIBackdrop", 0), false)
    for i = 0, 11 do
        --BlzFrameSetVisible(BlzGetFrameByName("CommandButton_"..i, 0), false) --отключить
        BlzFrameSetSize(BlzGetFrameByName("CommandButton_" .. i, 0), 0, 0)--скрыть, но работать будут по хоткеям
    end
    BlzHideOriginFrames(true)--скрыть всё
end

function ShowEverything(player)
    BlzFrameSetVisible(BlzGetFrameByName("ConsoleUIBackdrop", 0), GetLocalPlayer()==player)
    local normal=0
    if GetLocalPlayer()==player then
        normal=0.039
    end
    for i = 0, 11 do
        --BlzFrameSetVisible(BlzGetFrameByName("CommandButton_"..i, 0), false)
        BlzFrameSetSize(BlzGetFrameByName("CommandButton_" .. i, 0), normal, normal)
    end
    BlzHideOriginFrames(not GetLocalPlayer()==player)--скрыть всё
end

function CreateAllHeroInBox(lineK)
    local sx,sy=0.1,0.561
    local totalContent = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), '', 0) --пустышка, где будут все фреймы
    local allPortraits={}
    local step=0.039

    local strTable=HowHeroAtAttrib(1) --сила
    local intTable=HowHeroAtAttrib(2) -- инт
    local agiTable=HowHeroAtAttrib(3) -- аги
    local legTable=HowHeroAtAttrib(4) -- легендарный
    -- содаём героев атрибута сила
    if #strTable <=lineK then lineK=#strTable end
    local s=1+#strTable//lineK
    --print(s.."Столбцов")
    local k=1
    local total=1
    local lastY=0 --Последняя точка смещения
    for j=1,s do
        for i=1,lineK do
            if k<=#strTable+1 then
                allPortraits[total]=CreateGluePickHero(totalContent,sx+(i-1)*step,sy-(j-1)*step,step,nil)
                k=k+1
                total=total+1
                lastY=sy-(j-1)*step
            end
        end
    end
    --Смена линии по Y вниз
    sy=lastY-step*2
    -- содаём героев атрибута сила
    s=1+#intTable//lineK
    k=1
    for j=1,s do
        for i=1,lineK do
            if k<=#intTable+1 then
                allPortraits[total]=CreateGluePickHero(totalContent,sx+(i-1)*step,sy-(j-1)*step,step,nil)
                k=k+1
                total=total+1
                lastY=sy-(j-1)*step
            end
        end
    end

    --Смена линии по Y вниз
    sy=lastY-step*2
    -- содаём героев атрибута ловкость
    s=1+#agiTable//lineK
    k=1
    for j=1,s do
        for i=1,lineK do
            if k<=#agiTable+1 then
                allPortraits[total]=CreateGluePickHero(totalContent,sx+(i-1)*step,sy-(j-1)*step,step,nil)
                k=k+1
                total=total+1
                lastY=sy-(j-1)*step
            end
        end
    end

    --Смена линии по Y вниз
    sy=lastY-step*2
    -- содаём героев атрибута ловкость
    s=1+#legTable//lineK
    k=1
    for j=1,s do
        for i=1,lineK do
            if k<=#legTable+1 then
                allPortraits[total]=CreateGluePickHero(totalContent,sx+(i-1)*step,sy-(j-1)*step,step,nil)
                k=k+1
                total=total+1
                lastY=sy-(j-1)*step
            end
        end
    end
end



function CreateGluePickHero(parent,posX,posY,scale,texture)

    if not texture then
        texture = "ReplaceableTextures\\CommandButtons\\BTNCancel"
    end
    if not parent then
        parent= BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0)
    end
    local SelfFrame = BlzCreateFrameByType('GLUEBUTTON', 'FaceButton', parent, 'ScoreScreenTabButtonTemplate', 0)
    local buttonIconFrame = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', SelfFrame, '', 0)
    --BlzFrameSetVisible(SelfFrame, false)
    -- BlzFrameSetVisible(SelfFrame, GetLocalPlayer() == player)
    BlzFrameSetAllPoints(buttonIconFrame, SelfFrame)
    BlzFrameSetTexture(buttonIconFrame, texture, 0, true)
    BlzFrameSetSize(SelfFrame, scale, scale)
    BlzFrameSetAbsPoint(SelfFrame, FRAMEPOINT_CENTER, posX, posY)

    local ClickTrig = CreateTrigger()
    BlzTriggerRegisterFrameEvent(ClickTrig, SelfFrame, FRAMEEVENT_CONTROL_CLICK)
    TriggerAddAction(ClickTrig, function()
        print("Нажата кнопка ")
        BlzFrameSetEnable(BlzGetTriggerFrame(), false)
        BlzFrameSetEnable(BlzGetTriggerFrame(), true)
    end)

    local TrigMOUSE_ENTER = CreateTrigger()
    BlzTriggerRegisterFrameEvent(TrigMOUSE_ENTER, SelfFrame, FRAMEEVENT_MOUSE_ENTER)

    TriggerAddAction(TrigMOUSE_ENTER, function()
        print("показать подсказку ")

    end)
    local TrigMOUSE_LEAVE = CreateTrigger()
    BlzTriggerRegisterFrameEvent(TrigMOUSE_LEAVE, SelfFrame, FRAMEEVENT_MOUSE_LEAVE)
    TriggerAddAction(TrigMOUSE_LEAVE, function()
        print("убрать подсказку")

    end)


    return SelfFrame
end

AllHeroID={}
function CreateAllHeroID() -- создаём всех героев по 1 экземпляру
    local start=FourCC('H000')
    local endC=FourCC('H000')+2000
    local k=1
    for i=start,endC do
        AllHeroID[k]=CreateUnit(Player(PLAYER_NEUTRAL_PASSIVE),i,0,0,0)
        ShowUnit(AllHeroID[k],false)
        if AllHeroID[k] then
           -- print(GetUnitName(AllHeroID[k])..k)
            k=k+1
        end
    end
    print("создано "..#AllHeroID)
end

IsLegendary=FourCC('A02R')
function HowHeroAtAttrib(attrib) --1 str, 2 int, 3 agi, 4 legend
    local k=0
    local table={}

    for i=1,#AllHeroID do
        if GetUnitAbilityLevel(AllHeroID[i],IsLegendary)==0 then
            if BlzGetUnitIntegerField(AllHeroID[i],UNIT_IF_PRIMARY_ATTRIBUTE)==attrib  then
                table[k]=AllHeroID[i]
                k=k+1
            end
        else
            if attrib==4 then
                print("Опредлён легендарный герой "..GetUnitName(AllHeroID[i]))
                table[k]=AllHeroID[i]
                k=k+1
            end
        end
    end
    if attrib==1 then
        --print(k.. " героев тарибута сила")
    elseif attrib==2 then
       -- print(k.. " героев тарибута интеллект")
    elseif attrib==3 then
        --print(k.. " героев тарибута ловкость")
    end
    return table
end